image: node:16

stages:
  - .pre
  - test
  - build
  - release

variables:
  BAZEL_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

.job_build:
  script: &job_build |-
    apt-get update -y
    apt-get install cmake git libssl-dev libgmp-dev libtinfo5 libprotoc-dev wget -y
    apt-get install zlib1g-dev 
    npm install -g @bazel/bazelisk
    echo "machine $CI_SERVER_HOST login gitlab-ci-token password $CI_JOB_TOKEN" >> ~/.netrc
    export GOPRIVATE=${CI_SERVER_HOST}
    mkdir -p ./dist
    bazel version
    cp runtime/version/version.go /tmp/version.go
    sed -i "s/\\\u2692/${CI_COMMIT_SHORT_SHA}/g" runtime/version/version.go
    bazel build //beacon-chain:beacon-chain --config=release
    cp ./bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain ./dist/coordinator-beacon
    bazel build //validator:validator --config=release
    cp ./bazel-bin/cmd/validator/validator_/validator ./dist/coordinator-validator
    bazel build //tools/bootnode:bootnode --config=release
    cp ./bazel-bin/tools/bootnode/bootnode_/bootnode ./dist/coordinator-bootnode
    bazel build //tools/genesis-state-gen --config=release
    cp ./bazel-bin/tools/genesis-state-gen/genesis-state-gen_/genesis-state-gen ./dist/coordinator-genesis
    cp -r /tmp/version.go runtime/version/version.go

lint:
  stage: .pre
  image: golangci/golangci-lint:v1.52.2
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_TAG == null
      when: on_success
  script:
    - golangci-lint run -v --out-format=github-actions --config=.golangci.yml --out-format colored-line-number

test:
  stage: test
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_TAG == null
      when: on_success
  script:
    - apt-get update -y
    - apt-get install cmake git libssl-dev libgmp-dev libtinfo5 libprotoc-dev wget -y
    - npm install -g @bazel/bazelisk
    - echo "machine $CI_SERVER_HOST login gitlab-ci-token password $CI_JOB_TOKEN" >> ~/.netrc
    - export GOPRIVATE=${CI_SERVER_HOST}
    - bazel version
    - bazel test //api/...
    - bazel test //async/...
    - bazel test //cache/...
    - bazel test //cmd/...
    - bazel test //config/...
    - bazel test //container/...
    - bazel test //crypto/...
    - bazel test //encoding/...
    - bazel test //io/...
    - bazel test //math/...
    - bazel test //monitoring/...
    - bazel test //network/...
    - bazel test //proto/...
    - bazel test //runtime/...
    - bazel test //testing/...
    - bazel test //third_party/...
    - bazel test //time/...
    - bazel test //tools/...
    - bazel test //validator/...
    - bazel test //beacon-chain/blockchain/...
    - bazel test //beacon-chain/cache/...
    - bazel test //beacon-chain/core/...
    - bazel test //beacon-chain/db/...
    - bazel test //beacon-chain/forkchoice/...
    - bazel test //beacon-chain/gateway/...
    - bazel test //beacon-chain/monitor/...
    - bazel test //beacon-chain/node/...
    - bazel test //beacon-chain/operations/...
    - bazel test //beacon-chain/p2p/...
    - bazel test //beacon-chain/powchain/...
    - bazel test //beacon-chain/rpc/...
    - bazel test //beacon-chain/slasher/...
    - bazel test //beacon-chain/state/...
    - bazel test //beacon-chain/sync/...
#    - bazel test //build/...

build branch:
  stage: build
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_REF_NAME != "main" && $CI_COMMIT_TAG == null
      when: on_success
  script: *job_build
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - dist/coordinator-beacon
      - dist/coordinator-validator
      - dist/coordinator-bootnode
      - dist/coordinator-genesis

build latest:
  stage: build
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: on_success
  script: *job_build
  artifacts:
    name: "$CI_PROJECT_NAME-latest"
    paths:
      - dist/coordinator-beacon
      - dist/coordinator-validator
      - dist/coordinator-bootnode
      - dist/coordinator-genesis

release tag:
  stage: build
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_TAG != null
      when: on_success
  script: *job_build
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_BUILD_TAG"
    paths:
      - dist/coordinator-beacon
      - dist/coordinator-validator
      - dist/coordinator-bootnode
      - dist/coordinator-genesis

