image: l.gcr.io/google/bazel:latest

build:
  rules:
    - if: '$CI_COMMIT_TAG == null'
      when: manual
  tags:
    - docker
  script:
    - bazel build //beacon-chain:beacon-chain --config=release