image: node:16
stages:
  - test
  - build
  - release

.job_build:
  script: &job_build |-
    apt-get update -y
    apt-get install cmake git libssl-dev libgmp-dev libtinfo5 libprotoc-dev wget -y
    npm install -g @bazel/bazelisk
    echo "machine $CI_SERVER_HOST login gitlab-ci-token password $CI_JOB_TOKEN" >> ~/.netrc
    export GOPRIVATE=${CI_SERVER_HOST}
    echo "build --disk_cache=$CI_PROJECT_DIR/.cache" >> .bazelrc
    mkdir -p ./dist
    bazel version
    cp runtime/version/version.go /tmp/version.go
    sed -i "s/\\\u2692/${CI_COMMIT_SHORT_SHA}/g" runtime/version/version.go
    bazel build //beacon-chain:beacon-chain --config=release
    cp ./bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain ./dist/coordinator-beacon
    bazel build //validator:validator --config=release
    cp ./bazel-bin/cmd/validator/validator_/validator ./dist/coordinator-validator
    bazel build //tools/bootnode:bootnode --config=release
    cp ./bazel-bin/tools/bootnode/bootnode_/bootnode ./dist/coordinator-bootnode
    bazel build //tools/genesis-state-gen --config=release
    cp ./bazel-bin/tools/genesis-state-gen/genesis-state-gen_/genesis-state-gen ./dist/coordinator-genesis
    cp -r /tmp/version.go runtime/version/version.go

lint:
  stage: test
  image: golangci/golangci-lint:v1.52.2
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_REF_NAME != "main" && $CI_COMMIT_TAG == null
      when: on_success
  script: 
    - golangci-lint run -v --out-format=github-actions --config=.golangci.yml --out-format colored-line-number


build branch:
  stage: build
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_REF_NAME != "main" && $CI_COMMIT_TAG == null
      when: on_success
  script: *job_build
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - dist/coordinator-beacon
      - dist/coordinator-validator
      - dist/coordinator-bootnode
      - dist/coordinator-genesis

build latest:
  stage: build
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: on_success
  script: *job_build
  artifacts:
    name: "$CI_PROJECT_NAME-latest"
    paths:
      - dist/coordinator-beacon
      - dist/coordinator-validator
      - dist/coordinator-bootnode
      - dist/coordinator-genesis

release tag:
  stage: build
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_TAG != null
      when: on_success
  script: *job_build
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_BUILD_TAG"
    paths:
      - dist/coordinator-beacon
      - dist/coordinator-validator
      - dist/coordinator-bootnode
      - dist/coordinator-genesis

cache:
  key: bazel_cache
  paths:
    - .cache/