image: node:16
before_script:
  - apt-get update -y
  - apt-get install cmake git libssl-dev libgmp-dev libtinfo5 libprotoc-dev -y
  - npm install -g @bazel/bazelisk
  - echo "$GITCONFIG" > ~/.gitconfig
  - echo "build --disk_cache=$CI_PROJECT_DIR/.cache" >> .bazelrc

build:
  stage: build
#  rules:
#    - if: '$CI_COMMIT_TAG == null'
#      when: manual
  tags:
    - docker
  script:
    - bazel version
    - bazel build //beacon-chain:beacon-chain --config=release
    - bazel build //validator:validator --config=release
    - bazel build //tools/bootnode:bootnode --config=release
    - bazel build //tools/genesis-state-gen --config=release
    - mkdir -p ./dist
    - cp ./bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain ./dist/prysm-beacon
    - cp ./bazel-bin/cmd/validator/validator_/validator ./dist/prysm-coordinator
    - cp ./bazel-bin/tools/bootnode/bootnode_/bootnode ./dist/prysm-bootnode
    - cp ./bazel-bin/tools/genesis-state-gen/genesis-state-gen_/genesis-state-gen ./dist/prysm-genesis-generate
  artifacts:
    paths:
      - dist/prysm-beacon
      - dist/prysm-coordinator
      - dist/prysm-bootnode
      - dist/prysm-genesis-generate

cache:
  key: bazel_cache
  paths:
    - .cache/