run:
  skip-files:
    - .*_test.go
  skip-dirs:
    - beacon-chain/p2p/testing
    - beacon-chain/powchain/testing
    - beacon-chain/p2p/testing
    - proto/
    - contracts/
    - testing/
    - validator/web
  timeout: 10m
  go: '1.20'

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - unused
    - errcheck
    - gosimple
    - gocognit
    - dupword
    - nilerr
    - whitespace
    - misspell

linters-settings:
  golint:
    min-confidence: 0
  gocognit:
    min-complexity: 65
  misspell:
    locale: US
