run:
  skip-files:
    - validator/web/site_data.go
    - .*_test.go
  skip-dirs:
    - proto/
    - ^contracts/
    - testing/
  timeout: 10m
  go: '1.20'

linters:
  disable-all: true
  enable:
    - gosimple
    - goimports
    - gocognit
    - misspell
    - errcheck
    - gofmt
    - unused

linters-settings:
  golint:
    min-confidence: 0
  gocognit:
    min-complexity: 65
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

